### PR TITLE
Remove automatic localtunnel (crashes periodically)

### PR DESCRIPTION
**Pull request by endtwist**
@singram26 please r/m

### CODE REVIEW

**Comment by ilikescience** [comment]
@endtwist @singram26  what's the status on this? I want localtunnel gone like whoa.

**Comment by endtwist** [comment]
Should be done, check the dev branch?






On Wed, Jun 8, 2016 at 10:50 AM -0400, "Matthew Ström" <notifications@github.com> wrote:












@endtwist @singram26  what's the status on this? I want localtunnel gone like whoa.

**Comment by ilikescience** [comment]
@endtwist there ... is no dev branch?

**Comment by ilikescience** [comment]
@endtwist see previous comment ^

**Comment by endtwist** [comment]
@singram26 fixed, please review and merge

**Comment by samblackk** [comment]
@endtwist lgtm - mergin'

**Pull request merged**
