### PR TITLE
Better css handling

### PR DESCRIPTION
**Pull request by za-creature**
@endtwist Please r/m _after_ the other one

### CODE REVIEW

**Comment by endtwist** [comment]
Can you rebase, since tests are failing?

**Comment by za-creature** [comment]
Already rebased. Tests are failing because [coverage dropped](https://github.com/planetary/airframe/blob/732943524f00e399b5dcdb233e0d8628fe4af722/gulp/styles.js#L33)

Working on it atm.

**Comment by za-creature** [comment]
Bump

**Comment by endtwist** [comment]
Looking good. Guess I have some new tools to learn :) :+1:

**Pull request merged**
